### ISSUE TITLE
Salt makes encryption stronger

### ISSUE THREAD

**Issue by Varbin** [mosquito/simpleaes#1]
In your code when you use salts, you use CBC. And CBC is more secure than ECB because it obfuscate the result.
Please look here:
https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

**Comment by mosquito** [comment]
If you try to encrypt identical phrase more times with salt in theory your encryption key may be opened via differential analysis.

But when you sure what you not doing it. It's makes encryption stronger.

**Comment by Varbin** [comment]
Am 22.06.2014 15:18, schrieb Mosquito:

**Comment by mosquito** [comment]
Thank you very much for you interest. I added piece of that information in the README.

Say so looks better?

**Comment by Varbin** [comment]
Yes it does.

**Comment by mosquito** [comment]
Thank you very much for your interest to this project. I look forward to your other questions or corrections.

**Comment by Varbin** [comment]
Thank you for your fast reply.
